sudo: required
language: java
jdk: oraclejdk8
services:
  - docker
script:
  - gradle clean
  - gradle wrapper
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)